---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api-pod
          image: "{{ .Values.api_image_url }}:{{ .Values.api_image_tag }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
          env:
            - { name: INFERENCE_MODEL_URI, value: "http://{{ .Values.model_inference_service_name }}/predict" }
            - { name: MODEL_MONITORING_URI, value: "http:///{{ .Values.model_monitoring_service_name }}/pipeline_metrics" }
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq_service_name }}:{{ .Values.rabbitmq_service_port }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.rabbitmq_user }}"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: rabbitmq_password   
            - name: RABBITMQ_VHOST
              value: "{{ .Values.rabbitmq_vhost }}"
            - name: POSTGRES_USER
              value: {{ .Values.api_postgres_user }}
            - name: POSTGRES_DB
              value: {{ .Values.api_postgres_db }}
            - name: POSTGRES_PASSWORD   
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: api_postgres_password   
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SERVER
              value: {{ .Values.api_postgres_service_name }}
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]          
