---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-detection
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: claim-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: claim-detection
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: claim-detection
    spec:
      containers:
        - name: claim-detection-pod
          image: "{{ .Values.claim_detection_image_url }}:{{ .Values.claim_detection_image_tag }}"          
          imagePullPolicy: Always          
          resources:
            requests:
              cpu: 1
          env:           
            - name: POSTGRES_USER
              value: "{{ .Values.api_postgres_user }}"
            - name: POSTGRES_DB
              value: "{{ .Values.api_postgres_db }}"
            - name: POSTGRES_PASSWORD   
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: api_postgres_password   
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SERVER
              value: {{ .Values.api_postgres_service_name }}
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq_service_name }}:{{ .Values.rabbitmq_service_port }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.rabbitmq_user }}"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: rabbitmq_password   
            - name: RABBITMQ_VHOST
              value: "{{ .Values.rabbitmq_vhost }}"