---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api_postgres_service_name }}
  labels:
    app.kubernetes.io/name: {{ .Values.api_postgres_service_name }}
    app.kubernetes.io/component: server
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd-svc
  labels:
    app.kubernetes.io/name: milvus-etcd-svc
    app.kubernetes.io/component: server
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: milvus-etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio-svc
  labels:
    app.kubernetes.io/name: milvus-minio-svc
    app.kubernetes.io/component: server
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: milvus-minio
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone-svc
  labels:
    app.kubernetes.io/name: milvus-standalone-svc
    app.kubernetes.io/component: server
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: milvus-standalone
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
    - protocol: TCP
      port: 19530
      targetPort: 19530
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app.kubernetes.io/name: mongo-svc
    app.kubernetes.io/component: server
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
