---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.api_db_volume }}
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce # This should only ever be accessed by one mongoDB server instance
  resources:
    requests:
      # Need to have a look how big this will become.
      storage: 4Gi
  # TODO: Need to update depending on cluster setup
  storageClassName: {{ .Values.storage_class}}
  volumeMode: {{ .Values.volume_mode }}
