---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: db-seed
    app.kubernetes.io/name: db-seed-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db-seed
        app.kubernetes.io/name: db-seed-job
    spec:
      containers:
        - name: db-seed-container
          image: "{{ .Values.db_seed_image_url }}:{{ .Values.db_seed_image_tag }}"
          envFrom:
            - configMapRef:
                name: db-seed-config
          env:
            - name: DATA_DIR
              value: "/app/finnish_news_archieve"
            - name: FACEPAGER_DATA
              value: "/app/facepager_data{{ .Values.facepager_folder }}"            
          volumeMounts:
            - name: {{ .Values.hf_cache }}
              mountPath: /app/sentence-transformer-model
            - name: finnish-news-volume
              mountPath: /app/finnish_news_archieve
            - name: facepager-data-volume
              mountPath: /app/facepager_data
      restartPolicy: Never
      volumes:
        - name: {{ .Values.hf_cache }}
          persistentVolumeClaim:
            claimName: {{ .Values.hf_cache }}
        - name: finnish-news-volume
          persistentVolumeClaim:
            claimName: finnish-news-pvc
        - name: facepager-data-volume
          persistentVolumeClaim:
            claimName: facepager-data-pvc
  backoffLimit: 0