apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: db-seed
    app.kubernetes.io/name: db-seed-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db-seed
        app.kubernetes.io/name: db-seed-job
    spec:
      containers:
        - name: db-seed-container
          image: {{ .Values.dbSeed.image }}       
          volumeMounts:
            - name: hf-cache-volume
              mountPath: /app/sentence-transformer-model
            - name: finnish-news-volume
              mountPath: /app/finnish_news_archieve
            - name: facepager-data-volume
              mountPath: /app/facepager_data
      restartPolicy: Never
      volumes:
        - name: hf-cache-volume
          persistentVolumeClaim:
            claimName: hf-cache
        - name: finnish-news-volume
          persistentVolumeClaim:
            claimName: finnish-news-pvc
        - name: facepager-data-volume
          persistentVolumeClaim:
            claimName: facepager-data-pvc
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: db-seed
    app.kubernetes.io/name: db-seed-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db-seed
        app.kubernetes.io/name: db-seed-job
    spec:
      containers:
        - name: db-seed-container
          image: {{ .Values.dbSeed.image }}
          envFrom:
            - configMapRef:
                name: db-seed-config
          env:
            - name: SRC_FINNISH_NEWS_DIR
              value: {{ .Values.srcFinnishNewsDir }}
            - name: SRC_FACEPAGER_DATA
              value: {{ .Values.srcFacepagerData }}
          volumeMounts:
            - name: hf-cache-volume
              mountPath: /app/sentence-transformer-model
            - name: finnish-news-volume
              mountPath: /app/finnish_news_archieve
            - name: facepager-data-volume
              mountPath: /app/facepager_data
      restartPolicy: Never
      volumes:
        - name: hf-cache-volume
          persistentVolumeClaim:
            claimName: hf-cache-pvc
        - name: finnish-news-volume
          persistentVolumeClaim:
            claimName: finnish-news-pvc
        - name: facepager-data-volume
          persistentVolumeClaim:
            claimName: facepager-data-pvc
  backoffLimit: 0