---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-monitoring
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: model-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: model-monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: model-monitoring
    spec:
      containers:
        - name: model-monitoring-pod
          image: "{{ .Values.model_monitoring_image_url }}:{{ .Values.model_monitoring_image_tag }}"          
          imagePullPolicy: Always
          ports:
            - containerPort: 8096
          resources:
            requests:
              cpu: 125m
            limits: 
              cpu: 1000m
          env:            
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq_service_name }}:{{ .Values.rabbitmq_service_port }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.rabbitmq_user }}"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: rabbitmq_password
            - name: RABBITMQ_VHOST
              value: "{{ .Values.rabbitmq_vhost }}"
            - name: MONGO_HOST
              value: "{{ .Values.mongo_service_name }}:{{ .Values.mongo_service_port }}"
            - name: MONGO_USER
              value: "{{ .Values.mongo_user }}"
            - name: MONGO_DB
              value: "{{ .Values.mongo_monitoring_db }}"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: mongo_password    
