---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.model_monitoring_service_name }}
  labels:
    app.kubernetes.io/name: {{.Values.model_monitoring_service_name}}
    app.kubernetes.io/component: server
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
---