---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: rabbitmq-consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer-pod
          image: "{{ .Values.rabbitmq_consumer_image_url }}:{{ .Values.rabbitmq_consumer_image_tag }}"                    
          resources:
            requests:
              cpu: 1
          env:            
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq_service_name }}:{{ .Values.rabbitmq_service_port }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.rabbitmq_user }}"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databases
                  key: rabbitmq_password
            - name: RABBITMQ_VHOST
              value: "{{ .Values.rabbitmq_vhost }}"
