services:
  db:
    hostname: db
    container_name: postgres_db_container
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vector
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: apidev
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
    environment:
      - HF_HOME=/xml-roberta-model
      - SENTENCE_TRANSFORMERS_HOME=/sentence-transformer-model
    ports:
     - 8080:8080
    restart: always
    volumes:
      - xml-roberta-model:/app/xml-roberta-model
      - sentence-transformer-model:/app/sentence-transformer-model
      - logging:/app/logging
    depends_on:
      -  db
  dbseeding:
    build:
      context: .
      dockerfile: database/Dockerfile
    depends_on:
      -  db
    volumes:
      - ./database/data:/db/data
      - sentence-transformer-model:/db/sentence-transformer-model
      - logging:/db/logging

volumes:
  database:
  xml-roberta-model:
  sentence-transformer-model:
  logging:
