services:
  db:
    extends:
      file: ./api_service/docker-compose.yml
      service: db

  # pgvectorseeding:
    # build:
    #   context: .
    #   dockerfile: api/databases/pgvector/Dockerfile
    # depends_on:
    #   -  "db"
    # volumes:
    #   - ./api/databases/data:/db/data
    #   - sentence-transformer-model:/db/sentence-transformer-model
    #   - logging:/db/logging
    # networks:
    #   - backend

  api:
    extends:
      file: ./api_service/docker-compose.yml
      service: api  

  model_inference:
    extends:
      file: ./model_inference_service/docker-compose.yml
      service: model_inference
    environment:
      - MODEL_DIR=${MODEL_DIR}
      - MODEL_URI=${MODEL_URI}  
  
  web_scrape:
    extends:
      file: ./web_scrape/docker-compose.yml
      service: web_scrape

  model_monitoring_service:
    extends:
      file: ./model_monitoring_service/docker-compose.yml
      service: model_monitoring_service
  
  evidence_retrieval:
    extends:
      file: ./evidence_retrieval/docker-compose.yml
      service: evidence_retrieval
  
  milvus_standalone:
    extends:
      file: ./milvus_standalone/docker-compose.yml
      service: standalone
  
  etcd:
    extends:
      file: ./milvus_standalone/docker-compose.yml
      service: etcd
      
  minio:
    extends:
      file: ./milvus_standalone/docker-compose.yml
      service: minio
  
  db_seed:
    extends:
      file: ./milvus_standalone/docker-compose.yml
      service: db_seed

networks:
  backend:
    # Specify driver options
    driver: bridge    
volumes:
  database:
    driver: local  # Explicitly specify volume driver
  model_monitoring_data:
    name: model_monitoring_data
  # sentence-transformer-model:
  # xml-roberta-model:
  # logging:
