services:
  db:
    extends:
      file: ./api_service/docker-compose.yml
      service: db

  # pgvectorseeding:
    # build:
    #   context: .
    #   dockerfile: api/databases/pgvector/Dockerfile
    # depends_on:
    #   -  "db"
    # volumes:
    #   - ./api/databases/data:/db/data
    #   - sentence-transformer-model:/db/sentence-transformer-model
    #   - logging:/db/logging
    # networks:
    #   - backend

  api:
    extends:
      file: ./api_service/docker-compose.yml
      service: api  

  model_inference:
    extends:
      file: ./model_inference_service/docker-compose.yml
      service: model_inference
    environment:
      - MODEL_DIR=${MODEL_DIR}
      - MODEL_URI=${MODEL_URI}

  semantic_search:
    extends:
      file: ./semantic_search/docker-compose.yml
      service: semantic_search
    environment:
      - TEST_DATA_DIR=/app/test_data
      - TEST_METADATA_DIR=/app/test_metadata

  # https://github.com/milvus-io/milvus/blob/master/deployments/docker/standalone/docker-compose.yml
  etcd:
    extends:
      file: ./semantic_search/docker-compose.yml
      service: etcd

  minio:
    extends:
      file: ./semantic_search/docker-compose.yml
      service: minio

  standalone:
    extends:
      file: ./semantic_search/docker-compose.yml
      service: standalone

networks:
  backend:
    # Specify driver options
    driver: bridge    
volumes:
  database:
    driver: local  # Explicitly specify volume driver 
  # sentence-transformer-model:
  # xml-roberta-model:
  # logging:
