name: claim-model-training-env
channels:
  - conda-forge
dependencies:
  - pip
  - optuna==4.1.0
  - mlflow==2.19.0
  - wandb==0.19.1
  - datasets==3.2.0
  - sentence-transformers==3.3.1
  - evaluate==0.4.1
  - scikit-learn==1.6.0
  - pandas==2.2.3
  - numpy==2.2.1
  - matplotlib==3.10.0
  - seaborn==0.13.2
  - python-dotenv==1.0.1
  - ipykernel==6.29.5
  - pip:
    - torch==2.5.1
    - torchvision==0.20.1
    - torchaudio==2.5.1
    - transformers==4.47.1
    - huggingface_hub==0.26.5
    - git+https://github.com/Wauplin/setfit@dont-use-deprecated-dataset-filter
