services:
  model_monitoring_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - model_monitoring_data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/model_monitoring.db}
    ports:
      - "8093:8093"
    networks:
      - backend
  
networks:
  backend:
    driver: bridge

volumes:
  model_monitoring_data:
    name: model_monitoring_data