services:
  rabbitmq_consumer:
    build:
      context: .
      dockerfile: app/rabbitmq_consumer/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - backend
  model_monitoring_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8096:8096"
    depends_on:
      - mongodb
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge