services:
  rabbitmq_consumer:
    build:
      context: .
      dockerfile: app/rabbitmq_consumer/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend
    volumes:
      - mongodb_data:/app/data
  model_monitoring_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mongodb_data:/app/data
    ports:
      - "8096:8096"
    depends_on:
      - mongodb
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data