FROM ghcr.io/mlflow/mlflow:v2.20.1
# Install psycopg2
RUN pip install psycopg2-binary boto3

# Keep the original entrypoint
RUN apt-get -y update && \
    apt-get -y install python3-dev default-libmysqlclient-dev build-essential pkg-config && \
    pip install --upgrade pip && \
    pip install psycopg2-binary

CMD ["bash"]