---
apiVersion: v1
kind: Secret
metadata:
  name: factcheck
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData: 
  google_api_key: {{.Values.google_api_key}}
  id_fco: {{ .Values.id_fco }}
  id_ff: {{ .Values.id_ff }}
  id_snopes: {{ .Values.id_snopes }}

--- 
apiVersion: v1
kind: Secret
metadata:
  name: databases
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:   
  mongopassword: {{ randAlphaNum 48 | b64enc }}
  redispassword: {{ randAlphaNum 48 | b64enc }}
  api_postgres_password: {{ randAlphaNum 48 | b64enc }}
