services:
  db:
    hostname: db
    container_name: postgres_db_container
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vector
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
  api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: apidev
      command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
      ports:
      - 8080:8080
      restart: always
      depends_on:
        - "db"
      networks:
        - backend

networks:
  backend:
    driver: bridge    

volumes:
  database:
    driver: local  # Explicitly specify volume driver
