services:
  test_db:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on: 
      - "test_db"
