name: claim-detection-env
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - numpy
  - pandas
  - seaborn
  - mlflow
  - demoji
  - transformers
  - accelerate
  - sentencepiece
  - sentence-transformers
  - mlflow
  - optuna
  - pytorch
  - evaluate
