# Create base 64 encoded certificates as follows:
# openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout saml.key -out saml.crt -subj "/C=FI/ST=Uusimaa/L=Espoo/O=Aalto University/OU=IT/CN=llm.k8s-test.cs.aalto.fi"
# The output of the next line goes into the saml_certificate field
# cat saml.crt | base64 
# The output of the next line goes into the saml_private_key field
# cat saml.key | base64
google_api_key: <Google Custom Search Engine API key>
id_fco: <FactCheck.org Custom Search Engine ID>
id_ff: <FullFact Custom Search Engine ID>
id_snopes: <Snopes Custom Search Engine ID>
news_data_url: <URL for news data download
facepager_data_url: <URL for facepager Data>
model_data_url: <URL for model data>